<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.de-gupta</groupId>
        <artifactId>security.parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>security.janus</artifactId>
    <version>0.0.2-SNAPSHOT</version>

    <name>${project.artifactId}</name>
    <description>A library for authentication flow</description>
    <url>https://github.com/de-gupta/security.janus.git</url>

    <properties>
        <security.dependencies.bom.version>1.1.0</security.dependencies.bom.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.de-gupta</groupId>
                <artifactId>security.dependencies.bom</artifactId>
                <version>${security.dependencies.bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.github.de-gupta</groupId>
            <artifactId>aletheia</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.de-gupta</groupId>
            <artifactId>athena</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <scm>
        <connection>scm:git:ssh://git@github.com/de-gupta/security.janus.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/de-gupta/security.janus.git</developerConnection>
        <url>https://github.com/de-gupta/security.janus.git</url>
        <tag>HEAD</tag>
    </scm>
</project>