package de.gupta.security.janus.domain.model.signin;

public enum SigninFailureReason
{
	INVALID_CREDENTIALS,
	PROVIDER_UNAVAILABLE,
	PROVIDER_REJECTED,
	LOCAL_ACCOUNT_NOT_LINKED,
	LOCAL_ACCOUNT_DISABLED,
	UNSUPPORTED_PROVIDER,
	MALFORMED_COMMAND,
	UNEXPECTED_INTERNAL_FAILURE
}
