package de.gupta.security.janus.domain.model.signup;

public enum SignupFailureReason
{
	DUPLICATE_LOCAL_ACCOUNT,
	DUPLICATE_PROVIDER_IDENTITY,
	PROVIDER_PROVISIONING_FAILED,
	LOCAL_ACCOUNT_CREATION_FAILED,
	RECONCILIATION_REQUIRED,
	INVALID_INPUT,
	UNSUPPORTED_PROVIDER,
	UNEXPECTED_INTERNAL_FAILURE,
	PROVIDER_UNAVAILABLE,
	PROVIDER_REJECTED
}
